use crate::{DocBase, VarType};

pub fn gen_doc() -> Vec<DocBase> {
    vec![
        DocBase {
            var_type: VarType::Variable,
            name: "color.aqua",
            signatures: vec![],
            description: "Is a named constant for #00BCD4 color.",
            example: "",
            returns: "",
            arguments: "",
            remarks: "",
            links: "",
        },
        DocBase {
            var_type: VarType::Variable,
            name: "color.black",
            signatures: vec![],
            description: "Is a named constant for #363A45 color.",
            example: "",
            returns: "",
            arguments: "",
            remarks: "",
            links: "",
        },
        DocBase {
            var_type: VarType::Variable,
            name: "color.blue",
            signatures: vec![],
            description: "Is a named constant for #2196F3 color.",
            example: "",
            returns: "",
            arguments: "",
            remarks: "",
            links: "",
        },
        DocBase {
            var_type: VarType::Variable,
            name: "color.fuchsia",
            signatures: vec![],
            description: "Is a named constant for #E040FB color.",
            example: "",
            returns: "",
            arguments: "",
            remarks: "",
            links: "",
        },
        DocBase {
            var_type: VarType::Variable,
            name: "color.gray",
            signatures: vec![],
            description: "Is a named constant for #787B86 color.",
            example: "",
            returns: "",
            arguments: "",
            remarks: "",
            links: "",
        },
        DocBase {
            var_type: VarType::Variable,
            name: "color.green",
            signatures: vec![],
            description: "Is a named constant for #4CAF50 color.",
            example: "",
            returns: "",
            arguments: "",
            remarks: "",
            links: "",
        },
        DocBase {
            var_type: VarType::Variable,
            name: "color.lime",
            signatures: vec![],
            description: "Is a named constant for #00E676 color.",
            example: "",
            returns: "",
            arguments: "",
            remarks: "",
            links: "",
        },
        DocBase {
            var_type: VarType::Variable,
            name: "color.maroon",
            signatures: vec![],
            description: "Is a named constant for #880E4F color.",
            example: "",
            returns: "",
            arguments: "",
            remarks: "",
            links: "",
        },
        DocBase {
            var_type: VarType::Variable,
            name: "color.navy",
            signatures: vec![],
            description: "Is a named constant for #311B92 color.",
            example: "",
            returns: "",
            arguments: "",
            remarks: "",
            links: "",
        },
        DocBase {
            var_type: VarType::Variable,
            name: "color.olive",
            signatures: vec![],
            description: "Is a named constant for #808000 color.",
            example: "",
            returns: "",
            arguments: "",
            remarks: "",
            links: "",
        },
        DocBase {
            var_type: VarType::Variable,
            name: "color.orange",
            signatures: vec![],
            description: "Is a named constant for #FF9800 color.",
            example: "",
            returns: "",
            arguments: "",
            remarks: "",
            links: "",
        },
        DocBase {
            var_type: VarType::Variable,
            name: "color.purple",
            signatures: vec![],
            description: "Is a named constant for #9C27B0 color.",
            example: "",
            returns: "",
            arguments: "",
            remarks: "",
            links: "",
        },
        DocBase {
            var_type: VarType::Variable,
            name: "color.red",
            signatures: vec![],
            description: "Is a named constant for #FF5252 color.",
            example: "",
            returns: "",
            arguments: "",
            remarks: "",
            links: "",
        },
        DocBase {
            var_type: VarType::Variable,
            name: "color.silver",
            signatures: vec![],
            description: "Is a named constant for #B2B5BE color.",
            example: "",
            returns: "",
            arguments: "",
            remarks: "",
            links: "",
        },
        DocBase {
            var_type: VarType::Variable,
            name: "color.teal",
            signatures: vec![],
            description: "Is a named constant for #00897B color.",
            example: "",
            returns: "",
            arguments: "",
            remarks: "",
            links: "",
        },
        DocBase {
            var_type: VarType::Variable,
            name: "color.white",
            signatures: vec![],
            description: "Is a named constant for #FFFFFF color.",
            example: "",
            returns: "",
            arguments: "",
            remarks: "",
            links: "",
        },
        DocBase {
            var_type: VarType::Variable,
            name: "color.yellow",
            signatures: vec![],
            description: "Is a named constant for #FFEB3B color.",
            example: "",
            returns: "",
            arguments: "",
            remarks: "",
            links: "",
        },
    ]
}
